### ISSUE TITLE
Experience replay with frame stacking?

### ISSUE THREAD

**Issue by KristianHolsheimer** [deepmind/reverb#1]
Hi all! Thanks for open-sourcing this, I feel like the world has been waiting for a flexible experience replay framework.. I definitely have myself.

I was reading through the README and I was wondering if you might have an example of a replay buffer with frame stacking. How would I implement that?

Thanks!

**Comment by acassirer** [comment]
Hey Kristian! Great to hear that you are excited about Reverb!

There are a few different ways to implement frame stacking and depending on the use case the "optimal" approach may vary. I've created a colab to give an example of how you could do this and since I suspect that more than you might be interested in doing exactly this I'll add it to the example folder. I'll send it out for review now and I'll update this issue once it has been submitted.

Cheers!

**Comment by acassirer** [comment]
Example is now submitted. You can find it [here](https://github.com/deepmind/reverb/blob/master/examples/frame_stacking.ipynb).

**Comment by acassirer** [comment]
I'm going to close down this issue now but feel free to reopen if what I shared wasn't what you had in mind.

**Comment by KristianHolsheimer** [comment]
Thanks for the example notebook @acassirer 

From the two examples, I prefer the second, in which you don't multiply the memory footprint by `stack_size`.

I was actually hoping for a selector class similar to `reverb.selectors.Uniform`. Maybe something like
`reverb.selectors.UniformWithStacking`, which would do the stacking on the server side.

There are 2 things/requests I'd like to mention.
1. In your second example, the sampled stacks will always come from the same trajectory/episode. I'm looking for a way to sample stacks coming from multiple trajectories.
2. You might want to initialize the frame stack `deque` by filling it with the first frame (repeated).

Either way, thanks a bunch for the notebook, much appreciated!
