### ISSUE TITLE
Access to keys?

### ISSUE THREAD

**Issue by doylech** [deepmind/reverb#125]
I am using Reverb to store overlapping sequences of length `L` at each timestep. I am trying to implement a prioritization strategy where I update the priority for sequences other than the ones sampled. For example, let's say I sample from the replay buffer and get a sequence that ends with timestep `t`. I would like to update the priority for sequences that end with timesteps `t-1, t-2...` that is, those that appear within the sequence that ends with `t`. To do this with `Client.mutate_priorities` I believe I need the key associated with all items I wish to change, but in the sampling process I only get the key for the sequence ending in `t`.

The way I have approached this is to record the keys for timesteps as they are sampled and build a map between each timestep and key. Is there a more straightforward way to get access to the keys, for example, in bulk or when a sequence is created in the table? Or is there a more natural way to approach this within the Reverb framework?

**Comment by acassirer** [comment]
Hi,

I'm afraid that there isn't really any straightforward way of doing this without hacking the core of Reverb. Internally to DeepMind we have an extension which does something along this lines called the `TimeDiffusionExtension` but dependencies of its implementation makes it tricky to open source.

If you would like to go down this route then I would recommend you to take a look at [`InsertOnSampleExtension`](https://github.com/deepmind/reverb/blob/master/reverb/cc/table_extensions/insert_on_sample.h) as it gives you the gist of how you can start accessing the internals of the items as a side effect of sampling or inserts. This would however require that you take control over the entire build chain of Reverb so you might be better off building a custom solution yourself rather than relying on Reverb for this use case.

Sorry that I couldn't give you more positive advice.
