### ISSUE TITLE
Random seed

### ISSUE THREAD

**Issue by LinxiFan** [deepmind/reverb#25]
Hi, 

Is there a way to set random seed for Reverb to force deterministic sampling? In my test case, there is only one single-threaded client, so the insertion has no randomness. 

Thanks!

**Comment by acassirer** [comment]
Hey,

I'm afraid that is not something we currently support nor is it a feature that ever been requested before. Do you mind providing a bit more context of what you are looking to do?

Cheers,
Albin

**Comment by LinxiFan** [comment]
Hi Albin,

Thank you so much for your reply, and Merry Christmas! 

I've been using reverb in my other project. My use case is regression testing - given the same seed, I want to make sure that my algorithm is fully deterministic and reproducible, so that I have peace of mind when I refactor the code. I understand that distributed training has inherent system stochasticity, so I only do testing with a single thread. 

In fact, I'm very curious - how does your team test RL implementation without setting it deterministic? How do you make sure there is no silent bug introduced by refactoring? As we all know, it's very hard to tell whether a performance degradation is due to a new bug or simply RL's high variance.

**Comment by acassirer** [comment]
Hey Jim,

That seems like a very reasonable application. As for how my team tests RL implementations, it varies greatly between groups and individuals. However, in general I think that most people try to design "real" unit tests that span the entire algorithm end to end. What people usually do instead is to unit tests the individual components and then construct integrations tests that checks the learning behaviour in an E2E setting. This is often done at larger scale and the focus is not on achieving the exact same learning curves but instead of reproducing earlier results within some defined margin of error.

Back to your issue, I like the idea in general but it looks like it might be a bit tricky to get completely right. Instead, what I'd recommend you to do is to replace the non deterministic `Selector`s during the test if you want to do exact output checking. This obviously would change the learning behaviour of the agent but would allow you to verify that the refactoring did not change the behaviour.

One way to do this is to replace your `Table` with a `Table.queue`? If your agent needs to rely on higher `SamplesPerInsertRatio` then maybe something along the lines of:

```python

SPI = ...
table = reverb.Table(
  name="test_table",
  sampler=reverb.selector.Fifo(),
  remover=reverb.selector.Fifo(),
  max_size=100,
  max_times_sampled=SPI,
  rate_limiter=reverb.rate_limiters.SampleToInsert(
      samples_per_insert=SPI,
      min_size_to_sample=1,
      error_buffer=(0, 100)),
)
```

**Comment by LinxiFan** [comment]
This is very useful and insightful. Thank you so much for your explanation and advice!
