### ISSUE TITLE
CPP api

### ISSUE THREAD

**Issue by NicolayP** [deepmind/reverb#30]
Hi, is there a plan to provide a c++ api? I'm using tensorflow c++ api because my project has real time constraints and I would be nice to have a c++ implementation of a replay buffer.

**Comment by acassirer** [comment]
Hey,

Reverb is implemented in C++ and you could use that API directly. You'll find the code [here](https://github.com/deepmind/reverb/tree/master/reverb/cc) and if you want to then you are obviously free to use it directly instead of going through Python. 

That being said, I'm afraid that we can't promise any sort of stability in the C++ API. To give ourselves flexibility to quickly iterate we reserve the right to make fundamental changes to the internals and public methods in the C++ layer. If that seems fine to you (or if you simply want to use a pinned version) then there is nothing stopping you from reaching in and using the C++ API directly.

Cheers,
Albin
