### ISSUE TITLE
Replay buffer as in the IMPALA paper

### ISSUE THREAD

**Issue by thisiscam** [deepmind/reverb#40]
Hi,

The IMPALA paper states that:
 
<img width="400" alt="Screen Shot 2021-05-05 at 2 29 17 AM" src="https://user-images.githubusercontent.com/7684342/117104184-b40e8380-ad49-11eb-9645-2a8caada3d8c.png">

So my understanding is that, for a batch size of 100, 50 samples are drawn from new experiences, and 50 are drawn from a replay buffer. 
I am wondering how to implement this behavior using reverb?

Currently I'm thinking of maintaining two `Table`s. 
For the new experiences buffer, it will be a `Queue` just as in the README. 
For the replay buffer, I will sample uniformly, and set `max_times_sampled=1`. 

So perhaps something like this:
```python
new_size = 1000
replay_size = 100000
server = reverb.Server(
    tables=[
        reverb.Table(
            name='replay_buffer',
            sampler=reverb.selectors.Uniform(),
            remover=reverb.selectors.Fifo(), 
            max_size=replay_size,
            max_times_sampled=1,
            rate_limiter=reverb.rate_limiters.MinSize(1),
        ),
        reverb.Table.queue(name='new_experiences', max_size=new_size)
    ],
    port=8000,
)
```

However, the doc says:
> An item has been sampled more than the maximum number of times permitted by the Table’s rate limiter. Note that not all rate limiters will enforce this.

It's not clear what `max_times_sampled=1` do, and which rate limiters will actually enforce it. 

The `remover=reverb.selectors.Fifo()` is also suspicious since in my imagined use case, the remover should just always drop the sampled item every-time, leaving no place for a `remover` at all! 
Though perhaps this is a feature -- for example, if no sampling occurs (e.g. node failure), the buffer will get to its max_size, causing items to dropped in FIFO order?

**Comment by acassirer** [comment]
Hey,

Your setup looks (almost) perfectly sensible to me. All left is to create two dataset and join the result (e.g using [`tf.data.experimental.sample_from_datasets`](https://www.tensorflow.org/api_docs/python/tf/data/experimental/sample_from_datasets)).

As for what `max_times_sampled=1` do, it will trigger automatic removal of an item when it has been sampled once. The `remover`, as the name implies, also removes items but does so if the maximum size of the table is exceeded. Neither of these are affected/has any impact on the behaviour on the `rate_limiter` (which you have sensibly set to be very unrestrictive). 

Now for IMPALA, you would presumably insert all data into both the replay and the queue? If you then also sample from the queue and replay at 50%, and remove items from the replay after being sampled once, then the behaviour of the two will be almost identical (replay batches are uniformly selected from up to 1000 items while the queue batch is the 50 oldest items). This becomes obvious when you consider the fact that all ops on the two tables are more or less in sync and thus the rate limiting and size constraints on the queue will affect the replay buffer implicitly.

@fastturtle is more familiar with the details of IMPALA but it would be my guess that you do NOT want to set `max_times_sampled=1` but instead leave it as the default `max_times_sampled=0` (i.e don't remove items due to sampling). Your replay buffer would then (at steady state) contain the last 100k items and you would sample uniformly from these (which I believe is what you really want).

One final caveat is that I'd guess that you would also be better of to select a larger value for `MinSize` and/or set `max_times_sampled` to something other than `0` (but larger than 1, maybe 2 or 3?) to avoid overfitting to the first few items at the start of the training (i.e avoid sampling the first item 50 times in the first batch).

**Comment by thisiscam** [comment]
Thanks for the quick response!

>  All left is to create two dataset and join the result 
I'm still punting on this since currently my code base is in pytorch... might consider switch to JAX/TF if will make my life easier. 

> Now for IMPALA, you would presumably insert all data into both the replay and the queue?
Yes. Something like this:
```
client.insert(experience_item,
                priorities={
                    'replay_buffer': 1.0,
                    'new_experience': 1.0
                })
```

> (replay batches are uniformly selected from up to 1000 items while the queue batch is the 50 oldest items).
Why is the replay batch uniformly selected from up to 1000 items?  I thought setting `max_size=replay_size=100000` would imply that it is sampled from all 100000 items in the table?

According to DM's report on AlphaStar, which also uses IMPALA:
<img width="498" alt="Screen Shot 2021-05-05 at 4 16 09 AM" src="https://user-images.githubusercontent.com/7684342/117113562-a14f7b00-ad58-11eb-9a51-6638775f2c00.png">
I'm probably getting the idea of `retiring items in `replay_buffer` once it's sampled` from this report...

But perhaps these (the original IMPALA paper, and the AlphaStar report) are using very different replay strategies.

**Comment by thisiscam** [comment]
Ah! The appendix to the original IMPALA seems to say that the replay buffer is FIFO.
 
<img width="500" alt="Screen Shot 2021-05-05 at 4 23 42 AM" src="https://user-images.githubusercontent.com/7684342/117114317-af51cb80-ad59-11eb-8bee-fb707d9df1c5.png">

**Comment by acassirer** [comment]
Yes, and so is your setup?

**Comment by acassirer** [comment]
>Why is the replay batch uniformly selected from up to 1000 items? I thought setting max_size=replay_size=100000 would imply that it is sampled from all 100000 items in the table?

It is correct that in isolation it would be sampling from the 100k items. However since you insert it together with the queue then it would block if the queue was full (i.e 1000 items). Furthermore, the `max_times_sampled=1` would ensure that items are removed after one sample, i.e the same rate as the queue, so the queue and and replay would always have the same size and thus the replay buffer's effective max size would be 1000.

> According to DM's report on AlphaStar, which also uses IMPALA:
...
I'm probably getting the idea of retiring items in replay_buffer once it's sampled from this report...

Then maybe try with `max_times_sampled=2`? I think that in AlphaStar they didn't use a combination of a queue and a replay but rather just the replay part of the setup. I might be wrong though but the behaviour of replaying each item twice could be achieved by simply using a (probably smaller to ensure more on policy data) replay buffer with uniform sampling and drop the queue from the setup.

> Ah! The appendix to the original IMPALA seems to say that the replay buffer is FIFO.
Yes that is what I'd expect as well. If I remember correctly then the setup they were using at the time that IMPALA was developed didn't really support the `max_times_sampled=1` behaviour for replay setups so if you want to reproduce the result then setting it to `0` is probably the best approach.

**Comment by thisiscam** [comment]
@acassirer Thanks for the explanation! They were really helpful.

**Comment by acassirer** [comment]
No worries! Good luck with your research!
