### ISSUE TITLE
Reverb error while running DQN

### ISSUE THREAD

**Issue by Idate96** [deepmind/reverb#43]
I am training a DQN agent in acme but after a while in the training I get the following error (or info??) that gets repeated over and over 
```bash
[reverb/cc/selectors/prioritized.cc:213] Tree needs to be initialized because node with index 0 has approximation error 0.000137329, which exceeds the threshold of 0.0001
```
I searched in the code but could not find much. Any idea what's the cause of this? What's the approximation error of a node?

**Comment by acassirer** [comment]
Hey,

The message looks a bit more scary than it is and should be treated as info (i.e. not error). This message is coming from the  [`PrioritizedSelector`](https://github.com/deepmind/reverb/blob/master/reverb/cc/selectors/prioritized.cc#L213) and is emitted when enough floating point error has been aggregated to motivate a rebalancing of the sum tree. This all happens automatically and generally don't require any action on your side.

That being said, this message should not appear very frequently. The message signals that an expensive operation (`O(NlogN)` rather than `O(logN)`) so if it appears very frequently and your experiment is bottlenecked by Reverb then it might be worth while rethinking the magnitude of the priorities you are using. I'd say that this is very unlikely to be a problem but wanted to mention it just in case.
