### ISSUE TITLE
Removing absl's http_archive

### ISSUE THREAD

**Issue by thisiscam** [deepmind/reverb#50]
Hi,

I noticed that https://github.com/deepmind/reverb/blob/master/WORKSPACE#L31 hard codes upstream tensorflow's absl version as a `http_archive`.

Does this mean that reverb will only support the latest TF version? Currently if I try to use TF 2.4 with the latest master branch, I get very lousy errors like:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cyang/anaconda3/envs/myenv/lib/python3.8/site-packages/reverb/__init__.py", line 27, in <module>
    from reverb import item_selectors as selectors
  File "/Users/cyang/anaconda3/envs/myenv/lib/python3.8/site-packages/reverb/item_selectors.py", line 19, in <module>
    from reverb import pybind
  File "/Users/cyang/anaconda3/envs/myenv/lib/python3.8/site-packages/reverb/pybind.py", line 1, in <module>
    import tensorflow as _tf; from .libpybind import *; del _tf
ImportError: dlopen(/Users/cyang/anaconda3/envs/myenv/lib/python3.8/site-packages/reverb/libpybind.so, 2): Symbol not found: __ZN10tensorflow15TensorShapeBaseINS_11TensorShapeEEC2EN4absl12lts_202103244SpanIKxEE
  Referenced from: /Users/cyang/anaconda3/envs/myenv/lib/python3.8/site-packages/reverb/libpybind.so
  Expected in: flat namespace
 ```

The error is caused by mismatch in the absl version in the WORKSPACE file, and the absl version used by my pip installed tensorflow. 

A fix to this is probably to eliminate the use of that `http_archive`, then add the include rules for absl manually similar to how you did it for TF: https://github.com/deepmind/reverb/blob/master/reverb/cc/platform/default/repo.bzl#L186.
But since absl is actually right under `tensorflow/include/absl`, perhaps using tensorflow's includes everywhere is already sufficient?
I do see that probably internally you would still want to use those `@com_google_absl` targets for consistency. So I'm not sure what's the best resolution.

Another possible fix is to make tensorflow an external dependency, similar to how tensorflow_text did it: https://github.com/tensorflow/text/blob/master/WORKSPACE#L53. This should also avoid the absl inconsistency.

**Comment by ebrevdo** [comment]
There are a couple of reasons why we still rely on our own absl library, mainly because tensorflow's includes directory lacks all the absl headers (it only includes the ones that tensorflow uses, and we need additional headers).  So we still need to include our own.  At the same time, it needs to be the same version of absl that the tensorflow package is using because we compile tensorflow header code and it needs to use consistent absl versions as TF.

We have asked TF team to export the version of absl used (and its hash) so we can query it and get the right version when building; but it's not yet available in `tf.sysconfig`.  I'll leave this issue open until we do that.

We build Reverb nightlies against TF nightlies, which is why you can't use a Reverb nightly with TF 2.4.0.  If you want to use a version of Reverb with TF 2.4.0 you need to either use a release version of Reverb, built against TF 2.4.0, or you can manually check out reverb, modify the WORKSPACE file to point to the right version of absl, and build a package for yourself.

**Comment by thisiscam** [comment]
>  because tensorflow's includes directory lacks all the absl headers (it only includes the ones that tensorflow uses, and we need additional headers).

That is very reasonable. I haven't thought about that. Thanks for clarifying!
