### ISSUE TITLE
Segmentation fault on python 3.8 following instruction from acme

### ISSUE THREAD

**Issue by MichelangeloConserva** [deepmind/reverb#51]
Hello all,

I am trying to install dm-acme on python 3.8.

Following the instructions on the GitHub page, I installed
```
pip install dm-acme
pip install dm-acme[reverb]
pip install dm-acme[tf]
```
However I am getting a segmentation fault error when importing reverb.

`python3.8 crashed with SIGSEGV in tensorflow::OpDefBuilder::~OpDefBuilder()`

I am using the following package versions:
```
dm_acme-0.2.1-py3-none-any.whl
dm_reverb_nightly-0.3.0.dev20210617-cp38-cp38-manylinux2010_x86_64.whl
tfp_nightly-0.14.0.dev20210618-py2.py3-none-any.whl
tf_nightly-2.6.0.dev20210618-cp38-cp38-manylinux2010_x86_64.whl
tensorflow_metadata-1.0.0-py3-none-any.whl
```

Do you have any idea of the source of the issue?
Thanks.

Kind regards,
Michelangelo

**Comment by mwhoffman** [comment]
Hi! This issue is due to the mismatch between tf and reverb versions (see that reverb uses a nightly from the 17th and tf from the 18th), which itself is due to a problem with the reverb nightly being pushed on the 18th. This should be working now as all of the nightlies are updated to the 19th. 

In some sense, though, this is more of an Acme problem and on github that's been addressed with a quickfix in the form of https://github.com/deepmind/acme/commit/c7d3970d898c7b01be19d570a2740520984bc2e3 (and we'll roll out a better fix shortly).

**Comment by MichelangeloConserva** [comment]
Thank you very much for the quick response. It was very helpful.

Have a nice day!
