### ISSUE TITLE
Maybe flush() issue?

### ISSUE THREAD

**Issue by markub3327** [deepmind/reverb#92]
Hello,

  after 75 130 steps of training I get a warning about flush:

> [reverb/cc/trajectory_writer.cc:653] The number of pending items is alarmingly high, did you forget to call Flush? 0 items are waiting to be sent and 51 items have been sent to the server but haven't been confirmed yet. It is important to call Flush regularly as large numbers of pending items can result in OOM crashes on both client and server.

I'm using flush at the end of each episode.

## Code
```python
            # Check the end of episode
            if terminal:
                # Write the final interaction !!!
                writer.append({"observation": new_obs.astype("float32", copy=False)})
                writer.create_item(
                    table="experience",
                    priority=1.0,
                    trajectory={
                        "observation": writer.history["observation"][-2],
                        "action": writer.history["action"][-2],
                        "reward": writer.history["reward"][-2],
                        "next_observation": writer.history["observation"][-1],
                        "terminal": writer.history["terminal"][-2],
                    },
                )

                # Block until all the items have been sent to the server
                writer.end_episode()
                writer.flush()
```

Thanks.
Have a nice day.

**Comment by acassirer** [comment]
Hi,

It is exactly as the message is saying, the number of in flight items have grown above the warning threshold since you are not calling flush _often enough_. If your episodes are bounded (and fit in memory) then flushing between episodes should be enough but a more robust approach would be to call `flush` after each `create_item`. 

Calling `writer.flush()` will block until all items have been confirmed. This would almost definitely result in a slower acting loop so what you can do instead is to decide how much you want the actors to be able to run ahead and then call `flush` with that value. E.g. if you think it is fine for 10 items to be in-flight then you simply call `writer.flush(block_until_num_items=10)` after each `writer.create_item`. The flush call would thus only block if the server is starting to lag behind by more than 10 items (and if it is able to keep up then the `flush`-call would never block).

Please see the documentation of [`TrajectoryWriter.flush`](https://github.com/deepmind/reverb/blob/master/reverb/trajectory_writer.py#L348-L397) for more details.

Cheers,
Albin

PS: There is no need to call `writer.flush` after just calling `writer.end_episode` as the latter calls the former under the hood.

**Comment by markub3327** [comment]
@acassirer Yes, my episodes are bounded (1000 steps).

Is it better to run `writer.end_episode()` at the end of each episode and `writer.flush(block_until_num_items=10)` used at each step after the `writer.create_item`:
```python
if self._episode_steps > 1:
                writer.create_item(
                    table="experience",
                    priority=1.0,
                    trajectory={
                        "observation": writer.history["observation"][-2],
                        "action": writer.history["action"][-2],
                        "reward": writer.history["reward"][-2],
                        "next_observation": writer.history["observation"][-1],
                        "terminal": writer.history["terminal"][-2],
                    },
                )
```

**Comment by acassirer** [comment]
Yes exactly, `flush(10)` after each `create_item` **and** `end_episode` at the end of the episode.
